import { StatusCodes } from 'http-status-codes';

export const ACTIONS = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  BAD_REQUEST: 'BAD_REQUEST',
  NOT_FOUND: 'NOT_FOUND',
  FORBIDDEN: 'FORBIDDEN',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
} as const;

export const STATUS = {
  BAD_REQUEST: StatusCodes.BAD_REQUEST,
  CONFLICT: StatusCodes.CONFLICT,
  NOT_FOUND: StatusCodes.NOT_FOUND,
  UNAUTHORIZED: StatusCodes.UNAUTHORIZED,
  FORBIDDEN: StatusCodes.FORBIDDEN,
  INTERNAL_SERVER_ERROR: StatusCodes.INTERNAL_SERVER_ERROR,
} as const;

export const ERROR_CODES = {
  INVALID_REQUEST_BODY: 'INVALID_REQUEST_BODY',
  INVALID_REQUEST_PARAMS: 'INVALID_REQUEST_PARAMS',
  INVALID_USER_ROLE: 'INVALID_USER_ROLE',
  EMAIL_ALREADY_IN_USE: 'EMAIL_ALREADY_IN_USE',
  EMAIL_NOT_EXIST: 'EMAIL_NOT_EXISTS',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  CATEGORY_NOT_FOUND: 'CATEGORY_NOT_FOUND',
  CATEGORY_NAME_ALREADY_EXISTS: 'CATEGORY_NAME_ALREADY_EXISTS',
  UNEXPECTED_ERROR: 'UNEXPECTED_ERROR',
} as const;

export const ERROR_MESSAGES = {
  INVALID_USER_ROLE: 'You are not having the valid role to acess this action !',
};
