import { StatusCodes } from 'http-status-codes';

export const ACTIONS = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
} as const;

export const STATUS = {
  BAD_REQUEST: StatusCodes.BAD_REQUEST,
  CONFLICT: StatusCodes.CONFLICT,
  NOT_FOUND: StatusCodes.NOT_FOUND,
  INTERNAL_SERVER_ERROR: StatusCodes.INTERNAL_SERVER_ERROR,
} as const;

export const ERROR_CODES = {
  INVALID_REQUEST_BODY: 'INVALID_REQUEST_BODY',
  INVALID_REQUEST_PARAMS: 'INVALID_REQUEST_PARAMS',
  EMAIL_ALREADY_IN_USE: 'EMAIL_ALREADY_IN_USE',
  EMAIL_NOT_EXIST: 'EMAIL_NOT_EXISTS',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  UNEXPECTED_ERROR: 'UNEXPECTED_ERROR',
} as const;
